-- Enable RLS
alter table auth.users enable row level security;

-- Create profiles table (extends auth.users)
-- Create profiles table (extends auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  email text,
  first_name text,
  last_name text,
  role text default 'Client', -- 'Client', 'Developer', 'Admin'
  skills text,
  experience text,
  portfolio text,
  github_link text,
  is_approved boolean default false,
  phone text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on RLS for profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone"
  on profiles for select
  using ( true );

create policy "Users can update their own profile"
  on profiles for update
  using ( auth.uid() = id );

create policy "Users can insert their own profile"
  on profiles for insert
  with check ( auth.uid() = id );
  
-- Create Trigger to create profile on user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, username, role)
  values (new.id, new.email, new.raw_user_meta_data->>'username', coalesce(new.raw_user_meta_data->>'role', 'Client'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Create projects table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  service_type text not null,
  budget numeric,
  deadline date,
  status text default 'Pending', -- 'Pending', 'Open', 'In Progress', 'Completed', etc.
  client_id uuid references public.profiles(id) not null, -- Use profile ID (same as auth.uid)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for projects
alter table public.projects enable row level security;

create policy "Projects are viewable by everyone"
  on projects for select
  using ( true );

create policy "Clients can verify their own projects"
  on projects for insert
  with check ( auth.uid() = client_id );

create policy "Clients can update their own projects"
  on projects for update
  using ( auth.uid() = client_id );


-- Create tasks table
create table public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  project_id bigint references public.projects(id) on delete cascade not null,
  assigned_to uuid references public.profiles(id),
  budget numeric,
  deadline date,
  status text default 'Assigned',
  submission_git_link text,
  submission_notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for tasks
alter table public.tasks enable row level security;

create policy "Tasks are viewable by involved parties"
  on tasks for select
  using ( true ); -- Simplify for now, refine later

create policy "Admins can insert tasks"
  on tasks for insert
  with check ( exists (select 1 from profiles where id = auth.uid() and role = 'Admin') ); 
  -- Note: Initial seeding might need manual intervention or policy disable if running as anon for test, but keeping secure default for now.

create policy "Assigned developers can update tasks"
  on tasks for update
  using ( auth.uid() = assigned_to );


-- Create project applications table
create table public.project_applications (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id) on delete cascade not null,
  developer_id uuid references public.profiles(id) not null,
  cover_letter text,
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(project_id, developer_id)
);

-- RLS for applications
alter table public.project_applications enable row level security;

create policy "Developers can see their own applications"
  on project_applications for select
  using ( auth.uid() = developer_id );

create policy "Developers can apply"
  on project_applications for insert
  with check ( auth.uid() = developer_id );


-- Create messages table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references public.profiles(id) not null,
  receiver_id uuid references public.profiles(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for messages
alter table public.messages enable row level security;

create policy "Users can see their own messages"
  on messages for select
  using ( auth.uid() = sender_id or auth.uid() = receiver_id );

create policy "Users can verify their own messages"
  on messages for insert
  with check ( auth.uid() = sender_id );


-- Create payments table
create table public.payments (
  id bigint generated by default as identity primary key,
  project_id bigint references public.projects(id),
  payer_id uuid references public.profiles(id) not null,
  payee_id uuid references public.profiles(id),
  amount numeric not null,
  payment_type text default 'Incoming',
  status text default 'Pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for payments
alter table public.payments enable row level security;

create policy "Users can see their own payments"
  on payments for select
  using ( auth.uid() = payer_id or auth.uid() = payee_id );
