# Generated by Django 6.0 on 2026-02-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('Logo & Branding', 'Logo & Branding'), ('Poster / Banner Design', 'Poster / Banner Design'), ('Website Development', 'Website Development'), ('Web Application', 'Web Application'), ('Mobile App', 'Mobile App'), ('Digital Marketing', 'Digital Marketing'), ('SEO', 'SEO'), ('Maintenance & Support', 'Maintenance & Support'), ('Hosting & Deployment', 'Hosting & Deployment')], max_length=100),
        ),
    ]
